version: '3.8'
services:
  redis:
    image: redis:6.2
    restart: always
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 60s
      retries: 5
    ports:
      - '6379:6379'
  postgres:
    container_name: postgres
    restart: always
    ports:
       - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:14.5-alpine
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  worker:
    container_name: worker
    build:
      context: ./queue
    ports:
      - "3050:3050"
    volumes:
      - ./queue/src/:/app/src/
    depends_on:
      - redis
      - postgres
volumes:
  pgdata:
